// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjuyusuxkfbpnwlidqdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdXl1c3V4a2ZicG53bGlkcWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjIxMzUsImV4cCI6MjA2OTMzODEzNX0.kNwfv38H5PZqhT9L7th-vDHA6mrGT32ZuiqEZEBZHMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});